### ISSUE TITLE
Request to Consider Making the "LLMProject" Repository Public

### ISSUE THREAD

**Issue by Chenfeng-Li** [WilliamsJakeL/LLMProject#1]
Hi Jake,

I hope you're doing well! This is Chenfeng Li, your group partner from the attention kernel project in CMSC 35200 last autumn.

I'm currently working on my personal website and would like to refer this project as part of my portfolio. Since the repository is set to private, it can't be accessed by anyone outside our group or the TA, even if I fork it to my account. Would you consider making the repository public? If there are any concerns or issues with this, please let me know. Thanks a lot!

Best,
Chenfeng

**Comment by WilliamsJakeL** [comment]
Made public! Let me know if you need anything else.
